Cargo bug?  "vendored" feature seems to leak even outside of targeting
arm-unknown-linux-gnu-eabhif or aarch64-unknown-linux-gnu.

This makes sure we are building with the system OpenSSL instead of
the bundled one.

--- Cargo.toml.orig	2020-03-01 12:14:21 UTC
+++ Cargo.toml
@@ -26,9 +26,3 @@ postgres = "0.17.1"
 failure = "0.1.6"
 rayon = "1.3.0"
 semver = "0.9.0"
-
-[target.arm-unknown-linux-gnueabihf.dependencies]
-openssl = { version = "0.10.28", features = ["vendored"] }
-
-[target.aarch64-unknown-linux-gnu.dependencies]
-openssl = { version = "0.10.28", features = ["vendored"] }
