--- Cargo.toml.orig	2021-02-09 22:44:50 UTC
+++ Cargo.toml
@@ -31,7 +31,7 @@
 tokio-signal = "0.1"
 url = "1.7"
 xdg = "2.2"
-librespot = { version = "0.1.1", default-features = false, features = ["with-tremor"] }
+librespot = { version = "0.1.1", default-features = false }
 toml = "0.5.6"
 
 [target."cfg(target_os = \"macos\")".dependencies]
