--- widgetry/Cargo.toml.orig	2020-08-30 19:23:35 UTC
+++ widgetry/Cargo.toml
@@ -25,7 +25,7 @@ serde = "1.0.110"
 stdweb  = { version = "0.4.20", optional = true }
 stretch = "0.3.2"
 ttf-parser = "0.6.1"
-usvg = { git = "https://github.com/RazrFalcon/resvg", default-features=false }
+usvg = "0.11.0"
 webgl_stdweb = { version = "0.3", optional = true }
 winit = "0.22.2"
 
