--- kak-lsp.toml.orig	2018-12-18 02:50:14 UTC
+++ kak-lsp.toml
@@ -52,11 +52,16 @@ filetypes = ["python"]
 roots = ["requirements.txt", "setup.py", ".git", ".hg"]
 command = "pyls"
 
+#[language.c_cpp]
+#filetypes = ["c", "cpp"]
+#roots = ["compile_commands.json", ".cquery"]
+#command = "cquery"
+#args = ["--init={\"cacheDirectory\":\"/tmp/cquery\"}"]
+
 [language.c_cpp]
 filetypes = ["c", "cpp"]
-roots = ["compile_commands.json", ".cquery"]
-command = "cquery"
-args = ["--init={\"cacheDirectory\":\"/tmp/cquery\"}"]
+roots = ["compile_commands.json", ".ccls", ".git"]
+command = "ccls"
 
 [language.haskell]
 filetypes = ["haskell"]
