--- Cargo.toml.orig	2018-10-14 19:59:53 UTC
+++ Cargo.toml
@@ -1,6 +1,6 @@
 [package]
 name = "rabbiteer"
-version = "1.4.1"
+version = "1.4.1"
 authors = ["Martin Algesten <martin@algesten.se>"]
 description = "AMQP/RabbitMQ input/output CLI tool"
 repository = "https://github.com/algesten/rabbiteer-rs"
@@ -20,4 +20,5 @@ url = "1"
 #branch = "rabbiteer"
 #path = "/Users/martin/dev/_dist/rust-amqp"
 version = "0.1"
-default-features = false
+# commented out so we have TLS-enabled AMQP via OpenSSL
+# default-features = false
