--- Cargo.toml.orig	2020-09-04 12:25:25 UTC
+++ Cargo.toml
@@ -37,9 +37,6 @@ predicates = "0.5.0"
 assert_cmd = "0.4"
 tempfile = "3.0.2"
 
-[features]
-vendored-openssl = ['openssl/vendored']
-
 [[bin]]
 path = "src/main.rs"
 name = "cargo-generate"
