--- src/gopkg.in/cheggaaa/pb.v2/Gopkg.toml.orig	2017-06-04 15:08:13 UTC
+++ src/gopkg.in/cheggaaa/pb.v2/Gopkg.toml
@@ -79,8 +79,8 @@
   version = "1.5.0"
 
 [[constraint]]
-  name = "gopkg.in/mattn/go-colorable.v0"
-  version = "0.0.7"
+  name = "github.com/mattn/go-colorable"
+  version = "0.0.8"
 
 [[constraint]]
   name = "gopkg.in/mattn/go-isatty.v0"
