--- config/sidekiq.yml.orig	2017-09-06 12:59:04 UTC
+++ config/sidekiq.yml
@@ -24,3 +24,4 @@
   subscriptions_cleanup_scheduler:
     cron: '2 2 * * 0'
     class: Scheduler::SubscriptionsCleanupScheduler
+:pidfile: tmp/mastodon_workers.pid
