--- config/sidekiq.yml.orig	2018-01-24 12:29:46 UTC
+++ config/sidekiq.yml
@@ -30,3 +30,4 @@
   email_scheduler:
     cron: '0 10 * * 2'
     class: Scheduler::EmailScheduler
+:pidfile: /var/run/mastodon/mastodon_workers.pid
