--- config/sidekiq.yml.orig	2017-07-05 18:36:34 UTC
+++ config/sidekiq.yml
@@ -18,3 +18,4 @@
   doorkeeper_cleanup_scheduler:
     cron: '1 1 * * 0'
     class: Scheduler::DoorkeeperCleanupScheduler
+:pidfile: tmp/mastodon_workers.pid
