--- config/kibana.yml.orig	2018-11-04 16:33:12 UTC
+++ config/kibana.yml
@@ -112,3 +112,7 @@
 # The default locale. This locale can be used in certain circumstances to substitute any missing
 # translations.
 #i18n.defaultLocale: "en"
+
+# ml and reporting are not supported on FreeBSD
+xpack.ml.enabled: false
+xpack.reporting.enabled: false
